plugins {
    id 'com.android.application'
}

android {
    namespace 'com.thefxtrader.botzw'
    compileSdk 35
    buildToolsVersion = '37.0.0'

    defaultConfig {
        applicationId 'com.thefxtrader.botzw'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }
}
